In [1]:
import numpy as np

In [4]:
lst = [1,2,3,4]
arr = np.array(lst)
arr

array([1, 2, 3, 4])

In [5]:
type(arr)


numpy.ndarray

In [6]:
arr.shape

(4,)

In [7]:
lst1=[1,2,3,4,5]
lst2=[2,3,4,5,6]
lst3=[3,4,5,6,7]

arr1 = np.array([lst1,lst2,lst3])
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [8]:
arr1.shape

(3, 5)

In [ ]:
#size : 
#shape : tells us number of rows and columns present in an array
#ndim : 
#dtype :

In [ ]:
#indexing: one dimensional array
arr

array([1, 2, 3, 4])

In [10]:
arr[3]

np.int64(4)

In [11]:
#replace the element from the list

arr[3] =5
arr

array([1, 2, 3, 5])

In [12]:
#slicing
arr[-1]

np.int64(5)

In [13]:
arr[1]

np.int64(2)

In [14]:
arr[:]

array([1, 2, 3, 5])

In [15]:
arr[:-1]

array([1, 2, 3])

In [16]:
arr[1:]

array([2, 3, 5])

In [ ]:
arr[::-3]  # jump 3 steps

array([5, 1])

In [19]:
arr[::-2]  #jump two steps

array([5, 2])

In [ ]:
#slicing two dimensional array
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [ ]:
#question: call 1st column

arr1[:,1]   #challenge

array([2, 3, 4])

In [ ]:
arr1[1:,1:3]  #challenge

array([[3, 4],
       [4, 5]])

In [ ]:
arr1[:2,2:4]  #challenge

array([[3, 4],
       [4, 5]])

In [ ]:
arr1[1:, 3:5] #challenge

array([[5, 6],
       [6, 7]])

In [ ]:
arr1[:,3:5] #challenge

array([[4, 5],
       [5, 6],
       [6, 7]])

In [ ]:
arr1[:,::-4] #challenge***   #assignment question

array([[5, 1],
       [6, 2],
       [7, 3]])

In [47]:
#EDA techniques

arr<2

array([ True, False, False, False])

In [51]:
#To read the element present while checking the EDA technqiue

arr[arr<2]

array([1])

In [52]:
arr[arr<4]

array([1, 2, 3])

In [53]:
#identify the shape of array
arr1.shape

(3, 5)

In [55]:
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [54]:
#reshape mechanism

arr1.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 3, 4],
       [5, 6, 7]])

In [ ]:
arr1.reshape(5,4)  #this error tells us that the reshaping to be done only in the fixed parameter of the array shape, if the array shape is 5X3 than we can reshape to 3X5

ValueError: cannot reshape array of size 15 into shape (5,4)

SyntaxError: invalid syntax (2574031599.py, line 1)