# Topic: *Numpy*

**Numpy ?**
- NumPy is a general-purpose array-processing package. It provides a high-performance multidimensional array object, and tools for working with these arrays. It is the fundamental package for scientific computing with Python

**What is an array ?**
- An array is a data structure that stores values of same data type. In Python, this is the main difference between arrays and lists. While python lists can contain values corresponding to different data types, arrays in python can only contain values corresponding to same data type



In [2]:
import numpy as np

In [239]:
lst = [1,2,3,4]
arr = np.array(lst)
arr

array([1, 2, 3, 4])

In [240]:
type(arr)


numpy.ndarray

In [241]:
arr.shape

(4,)

In [242]:
lst1=[1,2,3,4,5]
lst2=[2,3,4,5,6]
lst3=[3,4,5,6,7]

arr1 = np.array([lst1,lst2,lst3])
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [243]:
arr1.shape

(3, 5)

In [244]:
#size : 
#shape : tells us number of rows and columns present in an array
#ndim : 
#dtype :

In [245]:
#indexing: one dimensional array
arr

array([1, 2, 3, 4])

In [246]:
arr[3]

np.int64(4)

In [247]:
#replace the element from the list

arr[3] =5
arr

array([1, 2, 3, 5])

In [248]:
#slicing
arr[-1]

np.int64(5)

In [249]:
arr[1]

np.int64(2)

In [250]:
arr[:]

array([1, 2, 3, 5])

In [251]:
arr[:-1]

array([1, 2, 3])

In [252]:
arr[1:]

array([2, 3, 5])

In [253]:
arr[::-3]  # jump 3 steps

array([5, 1])

In [254]:
arr[::-2]  #jump two steps

array([5, 2])

In [255]:
#slicing two dimensional array
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [256]:
#question: call 1st column

arr1[:,1]   #challenge

array([2, 3, 4])

In [257]:
arr1[1:,1:3]  #challenge

array([[3, 4],
       [4, 5]])

In [258]:
arr1[:2,2:4]  #challenge

array([[3, 4],
       [4, 5]])

In [259]:
arr1[1:, 3:5] #challenge

array([[5, 6],
       [6, 7]])

In [260]:
arr1[:,3:5] #challenge

array([[4, 5],
       [5, 6],
       [6, 7]])

In [261]:
arr1[:,::-4] #challenge***   #assignment question

array([[5, 1],
       [6, 2],
       [7, 3]])

In [262]:
#EDA techniques

arr<2

array([ True, False, False, False])

In [263]:
#To read the element present while checking the EDA technqiue

arr[arr<2]

array([1])

In [264]:
arr[arr<4]

array([1, 2, 3])

In [265]:
#identify the shape of array
arr1.shape

(3, 5)

In [266]:
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [267]:
#reshape mechanism

arr1.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 3, 4],
       [5, 6, 7]])

In [268]:
arr1.reshape(5,4)  #this error tells us that the reshaping to be done only in the fixed parameter of the array shape, if the array shape is 5X3 than we can reshape to 3X5

ValueError: cannot reshape array of size 15 into shape (5,4)

In [ ]:

#mechanism to create an array
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [ ]:
np.arange(1,10,1).shape

(9,)

In [ ]:
np.arange(1,20,2).reshape(2,5,1) #converted to 3 dimensional

array([[[ 1],
        [ 3],
        [ 5],
        [ 7],
        [ 9]],

       [[11],
        [13],
        [15],
        [17],
        [19]]])

In [ ]:
arr

array([1, 2, 3, 5])

In [ ]:
# multiple the same arr
arr

array([1, 2, 3, 5])

In [ ]:
arr * arr # where the element is multiplied with smae 

array([ 1,  4,  9, 25])

In [ ]:
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [ ]:
arr1 * arr1

array([[ 1,  4,  9, 16, 25],
       [ 4,  9, 16, 25, 36],
       [ 9, 16, 25, 36, 49]])

In [ ]:
one = np.ones((3,3))   #ones
one

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
zeros = np.zeros((3,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
one + zeros

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
#create an array using random generation : randint

np.random.randint(10,50,4).reshape(2,2)



array([[35, 35],
       [20, 38]], dtype=int32)

In [ ]:
#rand : return the normal distribution values between 0 and 1
np.random.rand(3,3)  

array([[0.66175371, 0.89829132, 0.51893797],
       [0.04490813, 0.46331219, 0.20571807],
       [0.55995616, 0.10057247, 0.00259075]])

In [ ]:
np.random.random_sample((2,5))  #return all number between 0 and 1

array([[0.3728091 , 0.43973087, 0.21189799, 0.30646118, 0.4983423 ],
       [0.33487014, 0.11890749, 0.41815672, 0.43391728, 0.33789478]])

# 📘 NumPy Add-on Material (Udemy Course)

> **Topic Overview:**  
> Supplementary resources and practical exercises designed to deepen understanding of NumPy fundamentals and advanced applications, as covered in the Udemy course.


> Lecture: 01: Numpy Array

In [ ]:
mylist = [1,2,3,4,5]   #one dimensional array
arr01  = np.array(mylist)
arr01

array([1, 2, 3, 4, 5])

In [8]:
type(arr01)

numpy.ndarray

In [ ]:
arr02 = [[1,2,3,4,5],[6,7,8,9,10]]   #two dimensional array
arr02 = np.array(arr02) 
arr02

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
np.arange(0,10)   #arange function

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(0,100,2)   #arange with step size

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [ ]:
np.zeros(3)   #zeros function for one dimensional array

array([0., 0., 0.])

In [14]:
np.zeros((3,3)) #zeros function for two dimensional array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [15]:
np.ones(4)  #ones function for one dimensional array

array([1., 1., 1., 1.])

In [16]:
np.ones((2,2)) #ones function for two dimensional array

array([[1., 1.],
       [1., 1.]])

In [17]:
np.linspace(0,10,5)  #linspace function

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [18]:
np.eye(4)   #identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [24]:
np.random.randn(4,4)   #return the normal distribution values with mean 0 and standard deviation 1  

array([[-0.09154208, -0.03695626, -0.65783526,  0.01085285],
       [ 0.61132357,  0.23086959, -0.0056831 ,  0.7481232 ],
       [ 0.20000493, -0.56921326, -1.26446558,  0.46486418],
       [-0.76600939, -0.53864631,  0.74970508, -1.43671154]])

In [29]:
np.random.rand(6)   #return the uniform distribution values between 0 and 1

array([0.27056487, 0.90824195, 0.48994007, 0.4874382 , 0.35374983,
       0.36100347])

In [30]:
np.random.randn(2,3)   #return the normal distribution values with mean 0 and standard deviation 1

array([[-0.32598592, -0.19561728,  0.75140612],
       [-0.82135408,  0.40935293,  0.24044229]])

In [ ]:
np.random.randint(10,50,(2,3)) #return random integers between 10 and 50 in an array of shape (2,3)

array([[11, 20, 15],
       [32, 44, 29]], dtype=int32)

In [34]:
np.random.randint(10,50,4).reshape(2,2) #return random integers between 10 and 50 in 2X2 array

array([[25, 39],
       [27, 45]], dtype=int32)

In [42]:
np.random.seed(30)  #setting the seed value for random number generation
np.random.rand(4)   #return random numbers after setting the seed

array([0.64414354, 0.38074849, 0.66304791, 0.16365073])

In [53]:
arr03 = np.arange(0,25)
arr03 = arr03.reshape(5,5)      #reshape to 5X5 matrix
arr03

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [54]:
narr = np.arange(1,101)  #create an array from 1 to 100
narr

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [58]:
narr.max()  #maximum value in the array

np.int64(100)

In [59]:
narr.min()  #minimum value in the array

np.int64(1)

In [63]:
narr.dtype  #data type of the array

dtype('int64')

In [64]:
narr.shape  #shape of the array

(100,)

In [66]:
narr.ndim  #number of dimensions of the array

1

In [67]:
narr.size  #size of the array

100

Lecture : 02: Indexing & Selection

In [68]:
arr04 = np.arange(0,11)
arr04

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [69]:
arr04[4] #accessing the element at index 4

np.int64(4)

In [70]:
arr04[1:4]

array([1, 2, 3])

In [72]:
arr04[0:5]

array([0, 1, 2, 3, 4])

In [73]:
arr04[:5]

array([0, 1, 2, 3, 4])

In [75]:
arr04[1:3] =50
arr04

array([ 0, 50, 50,  3,  4,  5,  6,  7,  8,  9, 10])

In [76]:
arr04[:]

array([ 0, 50, 50,  3,  4,  5,  6,  7,  8,  9, 10])

In [78]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [80]:
arr2d.shape

(3, 3)

In [ ]:
arr2d[0] #access first row

array([1, 2, 3])

In [85]:
arr2d[2] #access third row  

array([7, 8, 9])

In [86]:
arr2d[1][1]  #accessing element at second row and second column

np.int64(5)

In [ ]:
arr2d[0][2] #accessing element at first row and third column

np.int64(3)

In [ ]:
arr2d[0:2,1:3] #accessing sub array from two dimensional array

array([[2, 3],
       [5, 6]])

In [91]:
#conditional indexing
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr > 4 #conditional indexing

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [93]:
bool_arr = arr > 4
arr[bool_arr]  #accessing elements based on condition

array([ 5,  6,  7,  8,  9, 10])

In [ ]:
arr[bool_arr] #accessing elements based on condition

array([ 5,  6,  7,  8,  9, 10])

In [101]:
#exercise
# TASK: Use numpy to check how many rolls were greater than 2. For example if dice_rolls=[1,2,3] then the answer is 1.
# NOTE: Many different ways to do this! Your final answer should be an integer.

dice_rolls = np.array([3, 1, 5, 2, 5, 1, 1, 5, 1, 4, 2, 1, 4, 5, 3, 4, 5, 2, 4, 2, 6, 6, 3, 6, 2, 3, 5, 6, 5])
result = dice_rolls < 2
total_rolls_over_two = np.unique(dice_rolls[result])[0]
total_rolls_over_two


np.int64(1)

Lecture : 03: Numpy Operation

In [103]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [105]:
arr + 5 #adding 5 to each element

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [106]:
arr -2 #subtracting 2 from each element

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [107]:
arr + arr #adding two arrays element wise

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [109]:
arr -arr #subtracting two arrays element wise

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [110]:
arr * arr #multiplying two arrays element wise

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [111]:
arr/ arr #dividing two arrays element wise

C:\Users\admin\AppData\Local\Temp\ipykernel_1104\1498891668.py:1: RuntimeWarning: invalid value encountered in divide
  arr/ arr #dividing two arrays element wise


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [112]:
1/0

ZeroDivisionError: division by zero

In [113]:
1 / arr

C:\Users\admin\AppData\Local\Temp\ipykernel_1104\1528351372.py:1: RuntimeWarning: divide by zero encountered in divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [114]:
np.sqrt(arr)  #square root of each element in the array

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [115]:
np.log(arr)  #logarithm of each element in the array

C:\Users\admin\AppData\Local\Temp\ipykernel_1104\3583144439.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)  #logarithm of each element in the array


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [116]:
np.sin(arr)  #sine of each element in the array

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [117]:
np.exp(arr)  #exponential of each element in the array

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [118]:
np.std(arr)  #standard deviation of the array   

np.float64(2.8722813232690143)

In [119]:
np.mean(arr)  #mean of the array

np.float64(4.5)

In [120]:
np.median(arr)  #median of the array

np.float64(4.5)

In [122]:
np.dot(arr,arr)  #dot product of two array

np.int64(285)

In [123]:
np.sum(arr)  #sum of all elements in the array  

np.int64(45)

In [124]:
np.var(arr)  #variance of the array

np.float64(8.25)

In [125]:
arr2d = np.arange(0,25).reshape(5,5)      #reshape to 5X5 matrix
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [126]:
arr2d.shape

(5, 5)

In [ ]:
arr2d.sum(axis=0)  #sum of each column

array([50, 55, 60, 65, 70])

In [129]:
arr2d.sum(axis=1)  #sum of each row

array([ 10,  35,  60,  85, 110])

In [136]:
# TASK: Use numpy to check the total remaining in the account after the series of transactions.

account_transactions = np.array([100,-200,300,-400,100,100,-230,450,500,2000])
np.sum(account_transactions)

np.int64(2720)

np.int64(2720)