# Topic: *Numpy*

**Numpy ?**
- NumPy is a general-purpose array-processing package. It provides a high-performance multidimensional array object, and tools for working with these arrays. It is the fundamental package for scientific computing with Python

**What is an array ?**
- An array is a data structure that stores values of same data type. In Python, this is the main difference between arrays and lists. While python lists can contain values corresponding to different data types, arrays in python can only contain values corresponding to same data type

![My Project Diagram](notes/numpy_overview.png)



In [238]:
import numpy as np

In [239]:
lst = [1,2,3,4]
arr = np.array(lst)
arr

array([1, 2, 3, 4])

In [240]:
type(arr)


numpy.ndarray

In [241]:
arr.shape

(4,)

In [242]:
lst1=[1,2,3,4,5]
lst2=[2,3,4,5,6]
lst3=[3,4,5,6,7]

arr1 = np.array([lst1,lst2,lst3])
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [243]:
arr1.shape

(3, 5)

In [244]:
#size : 
#shape : tells us number of rows and columns present in an array
#ndim : 
#dtype :

In [245]:
#indexing: one dimensional array
arr

array([1, 2, 3, 4])

In [246]:
arr[3]

np.int64(4)

In [247]:
#replace the element from the list

arr[3] =5
arr

array([1, 2, 3, 5])

In [248]:
#slicing
arr[-1]

np.int64(5)

In [249]:
arr[1]

np.int64(2)

In [250]:
arr[:]

array([1, 2, 3, 5])

In [251]:
arr[:-1]

array([1, 2, 3])

In [252]:
arr[1:]

array([2, 3, 5])

In [253]:
arr[::-3]  # jump 3 steps

array([5, 1])

In [254]:
arr[::-2]  #jump two steps

array([5, 2])

In [255]:
#slicing two dimensional array
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [256]:
#question: call 1st column

arr1[:,1]   #challenge

array([2, 3, 4])

In [257]:
arr1[1:,1:3]  #challenge

array([[3, 4],
       [4, 5]])

In [258]:
arr1[:2,2:4]  #challenge

array([[3, 4],
       [4, 5]])

In [259]:
arr1[1:, 3:5] #challenge

array([[5, 6],
       [6, 7]])

In [260]:
arr1[:,3:5] #challenge

array([[4, 5],
       [5, 6],
       [6, 7]])

In [261]:
arr1[:,::-4] #challenge***   #assignment question

array([[5, 1],
       [6, 2],
       [7, 3]])

In [262]:
#EDA techniques

arr<2

array([ True, False, False, False])

In [263]:
#To read the element present while checking the EDA technqiue

arr[arr<2]

array([1])

In [264]:
arr[arr<4]

array([1, 2, 3])

In [265]:
#identify the shape of array
arr1.shape

(3, 5)

In [266]:
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [267]:
#reshape mechanism

arr1.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 3, 4],
       [5, 6, 7]])

In [268]:
arr1.reshape(5,4)  #this error tells us that the reshaping to be done only in the fixed parameter of the array shape, if the array shape is 5X3 than we can reshape to 3X5

ValueError: cannot reshape array of size 15 into shape (5,4)

In [ ]:

#mechanism to create an array
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [ ]:
np.arange(1,10,1).shape

(9,)

In [ ]:
np.arange(1,20,2).reshape(2,5,1) #converted to 3 dimensional

array([[[ 1],
        [ 3],
        [ 5],
        [ 7],
        [ 9]],

       [[11],
        [13],
        [15],
        [17],
        [19]]])

In [ ]:
arr

array([1, 2, 3, 5])

In [ ]:
# multiple the same arr
arr

array([1, 2, 3, 5])

In [ ]:
arr * arr # where the element is multiplied with smae 

array([ 1,  4,  9, 25])

In [ ]:
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [ ]:
arr1 * arr1

array([[ 1,  4,  9, 16, 25],
       [ 4,  9, 16, 25, 36],
       [ 9, 16, 25, 36, 49]])

In [ ]:
one = np.ones((3,3))   #ones
one

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
zeros = np.zeros((3,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
one + zeros

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
#create an array using random generation : randint

np.random.randint(10,50,4).reshape(2,2)



array([[35, 35],
       [20, 38]], dtype=int32)

In [ ]:
#rand : return the normal distribution values between 0 and 1
np.random.rand(3,3)  

array([[0.66175371, 0.89829132, 0.51893797],
       [0.04490813, 0.46331219, 0.20571807],
       [0.55995616, 0.10057247, 0.00259075]])

In [ ]:
np.random.random_sample((2,5))  #return all number between 0 and 1

array([[0.3728091 , 0.43973087, 0.21189799, 0.30646118, 0.4983423 ],
       [0.33487014, 0.11890749, 0.41815672, 0.43391728, 0.33789478]])