# Topic: *Pandas*

**Pandas ?**
- Pandas is a Python library used for working with data sets.

- It has functions for analyzing, cleaning, exploring, and manipulating data.

- The name "Pandas" has a reference to both "Panel Data", and "Python Data Analysis" and was created by Wes McKinney in 2008.

- Data analysis requires lots of processing, such as restructuring, cleaning or merging, etc. There are different tools are   
  available for fast data processing, such as Numpy, Scipy, Cython, and Panda. But we prefer Pandas because working with Pandas is fast, simple and more expressive than other tools.

- Pandas is built on top of the Numpy package, means Numpy is required for operating the Pandas.



Series: series is a data structure in pandas that hold an array  of information along with named index

- formal defination: one-dimensional ndarray with axis labels

In [5]:
import numpy as np
import pandas as pd

- Numpy array has numeric index

- pandas series add on a labeled index

In [12]:
myindex = ['USA', 'Canada', 'Mexico'] # custom index for the series
mydata = [1776, 1867, 1821] # data for the series

In [13]:
myser = pd.Series(index=myindex, data=mydata) # creating a pandas series
print(myser)

USA       1776
Canada    1867
Mexico    1821
dtype: int64


In [14]:
type(myser) # to check the type of the series

pandas.core.series.Series

In [15]:
myser['Canada'] # accessing data using custom index

np.int64(1867)

In [17]:
myser[0] # accessing data using default numeric index

C:\Users\admin\AppData\Local\Temp\ipykernel_10472\3672126530.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  myser[0] # accessing data using default numeric index


np.int64(1776)

In [20]:
ages = {'John': 5, 'Alice': 10, 'Bob': 7}  # dictionary of ages
age_series = pd.Series(ages) # creating a pandas series from the dictionary
print(age_series) # printing the series

John      5
Alice    10
Bob       7
dtype: int64


In [26]:
#exercise

#TASK: Use pandas to grab the expenses paid by Bob.
# MAKE SURE TO READ THE FULL INSTRUCTIONS ABOVE CAREFULLY, AS THE EVALUATION SCRIPT IS VERY STRICT.
#  Link to Solution: https://gist.github.com/Pierian-Data/3d7f7cb3528f015d9584d04a7168b97f

expenses = pd.Series({'Andrew':200,'Bob':150,'Claire':450})

bob_expenses =expenses["Bob"]
# bob_expense = # Use pandas, don't just manually write in the number here.expensesexpenses
print("bob_expense: ", bob_expenses)

bob_expense:  150


In [6]:
#imaginary Sales Data for 1st and 2nd quarter for global company
q1 = pd.Series({'Japan':80,'China':450,'India':200, 'USA':250})
q2 = pd.Series({'Brazil':100,'China':500,'India':200,'USA':260})

In [7]:
sales_Q1 =pd.Series(q1) # creating series for sales in Q1
sales_Q2 =pd.Series(q2) # creating series for sales in Q2

In [8]:
sales_Q1 #  viewing sales in Q1

Japan     80
China    450
India    200
USA      250
dtype: int64

In [10]:
sales_Q2 # viewing sales in Q2

Brazil    100
China     500
India     200
USA       260
dtype: int64

In [11]:
sales_Q1["Japan"] # accessing sales data for Japan in Q1

np.int64(80)

In [12]:
sales_Q1[0] # accessing sales data for Japan in Q1 using default numeric index

C:\Users\admin\AppData\Local\Temp\ipykernel_21076\3680541565.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  sales_Q1[0] # accessing sales data for Japan in Q1 using default numeric index


np.int64(80)

In [14]:
sales_Q1.keys() # viewing all the keys (countries) in sales_Q1

Index(['Japan', 'China', 'India', 'USA'], dtype='object')

In [15]:
sales_Q1.values # viewing all the sales values in sales_Q1

array([ 80, 450, 200, 250])

In [19]:
list = [1,2] * 2 # list replication
expected_output = np.array([1,2]) * 2 # numpy array replication
expected_output

array([2, 4])

In [20]:
#similiarly we can perform arithmetic operations on pandas series
sales_Q1 * 2 # multiplying all sales values in Q1 by 2

Japan    160
China    900
India    400
USA      500
dtype: int64

In [21]:
sales_Q1/1000 # converting sales values in Q1 from units to thousands

Japan    0.08
China    0.45
India    0.20
USA      0.25
dtype: float64

In [22]:
sales_Q1 + sales_Q2 # adding sales data for Q1 and Q2, aligning by index

Brazil      NaN
China     950.0
India     400.0
Japan       NaN
USA       510.0
dtype: float64

In [23]:
sales_Q1.add(sales_Q2, fill_value=0) # adding sales data for Q1 and Q2, filling missing values with 0   

Brazil    100.0
China     950.0
India     400.0
Japan      80.0
USA       510.0
dtype: float64

DataFrame: is a table with rows and column that can be easily restructure and filtered

- formal defination: a group of pandas series object that share the same index

In [24]:
import numpy as np
import pandas as pd

In [30]:
np.random.seed(101)  # for reproducibility
mydata = np.random.randint(0,101,(4,3)) # generating random integers between 0 and 100 in a 4x3 array
mydata

array([[95, 11, 81],
       [70, 63, 87],
       [75,  9, 77],
       [40,  4, 63]], dtype=int32)

In [32]:
myindex = ['USA', 'Canada', 'Mexico',"India"] # custom index for the rows
mycolumns = ['Jan', 'Feb', 'Mar'] # custom index for the columns
df = pd.DataFrame(data = mydata, index = myindex, columns = mycolumns) # creating a pandas DataFrame
df # viewing the DataFrame

Jan  Feb  Mar
USA      95   11   81
Canada   70   63   87
Mexico   75    9   77
India    40    4   63

In [33]:
df.info() # getting information about the DataFrame

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, USA to India
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Jan     4 non-null      int32
 1   Feb     4 non-null      int32
 2   Mar     4 non-null      int32
dtypes: int32(3)
memory usage: 252.0+ bytes


In [ ]:
pwd # checking current working directory

'c:\\Users\\admin\\OneDrive - BOMBAY COATED AND SPECIAL STEELS PRIVATE LIMITED\\Desktop\\ml-algorithms-practice\\notebooks'

In [ ]:
ls # listing files in the current directory

In [48]:
df = pd.read_csv("C:\\Users\\admin\\OneDrive - BOMBAY COATED AND SPECIAL STEELS PRIVATE LIMITED\\Desktop\\ml-algorithms-practice\\data\\tips.csv") # reading a CSV file into a DataFrame
df

total_bill   tip     sex smoker   day    time  size  price_per_person  \
0         16.99  1.01  Female     No   Sun  Dinner     2              8.49   
1         10.34  1.66    Male     No   Sun  Dinner     3              3.45   
2         21.01  3.50    Male     No   Sun  Dinner     3              7.00   
3         23.68  3.31    Male     No   Sun  Dinner     2             11.84   
4         24.59  3.61  Female     No   Sun  Dinner     4              6.15   
..          ...   ...     ...    ...   ...     ...   ...               ...   
239       29.03  5.92    Male     No   Sat  Dinner     3              9.68   
240       27.18  2.00  Female    Yes   Sat  Dinner     2             13.59   
241       22.67  2.00    Male    Yes   Sat  Dinner     2             11.34   
242       17.82  1.75    Male     No   Sat  Dinner     2              8.91   
243       18.78  3.00  Female     No  Thur  Dinner     2              9.39   

             Payer Name         CC Number Payment ID  
0    Christy Cunningham  3560325168603410    Sun2959  
1        Douglas Tucker  4478071379779230    Sun4608  
2        Travis Walters  6011812112971322    Sun4458  
3      Nathaniel Harris  4676137647685994    Sun5260  
4          Tonya Carter  4832732618637221    Sun2251  
..                  ...               ...        ...  
239       Michael Avila  5296068606052842    Sat2657  
240      Monica Sanders  3506806155565404    Sat1766  
241          Keith Wong  6011891618747196    Sat3880  
242        Dennis Dixon     4375220550950      Sat17  
243     Michelle Hardin  3511451626698139    Thur672  

[244 rows x 11 columns]