#Numpy parctise question

In [1]:
import numpy as np
import pandas as pd

In [ ]:
#Q1.Create a 1D NumPy array of integers from 10 to 50 (inclusive) and extract only the elements that are multiples of 5.

In [4]:
result = np.arange(10,51)
result = result[result % 5 ==0]
print(result)

[10 15 20 25 30 35 40 45 50]


In [ ]:
#Q2.Generate a 3×3 matrix with values ranging from 2 to 10, then find its transpose.

In [9]:
arr1 = np.arange(2,11).reshape(3,3).transpose()
arr1

array([[ 2,  5,  8],
       [ 3,  6,  9],
       [ 4,  7, 10]])

In [ ]:
#arr = np.array([[2, 4, 6],
                [1, 3, 5],
                [7, 9, 11]])
#Find the sum of each column and the maximum value of each row.

In [12]:
arr = np.array([[2, 4, 6],
                [1, 3, 5],
                [7, 9, 11]])
sum1 = np.sum(arr, axis = 0) #column-wise
print(sum1)
max = np.max(arr, axis = 1) #row-wise 
print(max)

[10 16 22]
[ 6  5 11]


In [ ]:
#Q4.Create two 3×3 matrices filled with random integers (between 1 and 10) and perform matrix multiplication.

In [23]:
matrix1 = np.random.randint(1,11, size=(3,3))
print(matrix1)

matrix2 = np.random.randint(1,11, size= (3,3))
print(matrix2)

matrix_product = np.matmul(matrix1, matrix2)
print(matrix_product)

[[ 9 10 10]
 [ 9  6  4]
 [ 7  4  1]]
[[ 7  3  1]
 [ 2  5  6]
 [ 1 10  3]]
[[ 93 177  99]
 [ 79  97  57]
 [ 58  51  34]]


In [ ]:
#Q5. Create a 4×4 NumPy array with values from 1 to 16, then replace all elements divisible by 3 with -1.

In [24]:
arr2 = np.arange(1,17).reshape(4,4)
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [28]:
arr2[arr2 % 3 == 0] = -1
print(arr2)

[[ 1  2 -1  4]
 [ 5 -1  7  8]
 [-1 10 11 -1]
 [13 14 -1 16]]


#pandas practise question

In [ ]:
#Q6.Create a Pandas DataFrame from the dictionary below and display the rows where Age > 25:
data = {
    'Name': ['Amit', 'Rahul', 'Priya', 'Sneha', 'Vikram'],
    'Age': [22, 27, 24, 29, 31],
    'Salary': [25000, 40000, 30000, 45000, 50000]
}

In [29]:
data = {
    'Name': ['Amit', 'Rahul', 'Priya', 'Sneha', 'Vikram'],
    'Age': [22, 27, 24, 29, 31],
    'Salary': [25000, 40000, 30000, 45000, 50000]
}

In [ ]:
df = pd.DataFrame(data)
df

Name  Age  Salary
0    Amit   22   25000
1   Rahul   27   40000
2   Priya   24   30000
3   Sneha   29   45000
4  Vikram   31   50000

In [34]:
df[df['Age']> 25]

Name  Age  Salary
1   Rahul   27   40000
3   Sneha   29   45000
4  Vikram   31   50000

In [ ]:
#Q7. Using the same DataFrame, add a new column named Bonus that is 10% of the Salary.

In [35]:
df['Bonus']= df['Salary']*0.1
df

Name  Age  Salary   Bonus
0    Amit   22   25000  2500.0
1   Rahul   27   40000  4000.0
2   Priya   24   30000  3000.0
3   Sneha   29   45000  4500.0
4  Vikram   31   50000  5000.0

In [ ]:
# Q8. Create a new DataFrame with:

'Department': ['IT', 'HR', 'Finance', 'IT', 'HR']

In [42]:
df = pd.DataFrame(data = {
    'Name': ['Amit', 'Rahul', 'Priya', 'Sneha', 'Vikram'],
    'Age': [22, 27, 24, 29, 31],
    'Salary': [25000, 40000, 30000, 45000, 50000],
    'Department': ['IT', 'HR', 'Finance', 'IT', 'HR']
}
)
df

Name  Age  Salary Department
0    Amit   22   25000         IT
1   Rahul   27   40000         HR
2   Priya   24   30000    Finance
3   Sneha   29   45000         IT
4  Vikram   31   50000         HR

In [47]:
result = df.set_index('Department')
result

Name  Age  Salary
Department                     
IT            Amit   22   25000
HR           Rahul   27   40000
Finance      Priya   24   30000
IT           Sneha   29   45000
HR          Vikram   31   50000

In [ ]:
#Q9. Using the merged DataFrame, group by Department and calculate the average Salary per department.

In [52]:
result1 = df.groupby('Department')['Salary'].mean()
result1

Department
Finance    30000.0
HR         45000.0
IT         35000.0
Name: Salary, dtype: float64

In [ ]:
#Q10. From the merged DataFrame, replace all NaN values (if any) in the Bonus column with 0 and display the result.

In [55]:
df = pd.DataFrame(data = {
    'Name': ['Amit', 'Rahul', 'Priya', 'Sneha', 'Vikram'],
    'Age': [22, 27, 24, 29, 31],
    'Salary': [25000, 40000, 30000, 0, 50000],
    'Department': ['IT', 'HR', 'Finance', 'IT', 'HR']
}
)
df

Name  Age  Salary Department
0    Amit   22   25000         IT
1   Rahul   27   40000         HR
2   Priya   24   30000    Finance
3   Sneha   29       0         IT
4  Vikram   31   50000         HR

In [68]:
df['Salary'] = df['Salary'].replace(0, 'NA')
df['Salary']
df

Name  Age Salary Department
0    Amit   22  25000         IT
1   Rahul   27  40000         HR
2   Priya   24  30000    Finance
3   Sneha   29     NA         IT
4  Vikram   31  50000         HR